version: '2'
services:
  slave-1:
    image: redis:cluster-v4
    network_mode: host
    ports:
        - "6382:6379"
#    command: redis-server  /etc/redis/redis-master.conf
    command: redis-server  --slaveof redis-master 6379
#    volumes:
#     - ./
    restart: unless-stopped
