version: '2'
services:
  master:
    image: redis:cluster-v4
    network_mode: host
    ports:
        - "6379:6379"
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
#    command: redis-server /etc/redis/redis-master.conf
    restart: unless-stopped

